# Generated by Django 3.0.4 on 2020-06-08 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cardriver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driversName', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=40)),
                ('carType', models.CharField(max_length=40)),
                ('carColor', models.CharField(max_length=40)),
                ('carNumber', models.CharField(max_length=40)),
                ('carStatus', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameOf_office', models.CharField(max_length=30)),
                ('officeLocation', models.CharField(max_length=30)),
                ('officePhone', models.CharField(max_length=30)),
                ('TransportFrom', models.CharField(max_length=30)),
                ('TransportTo', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=30)),
                ('cardriver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Transportation_office.Cardriver')),
            ],
        ),
    ]
